                                                                                                                                                                                                             class Solution {
                                                                                                                                                                                                                    public boolean isAlienSorted(String[] words, String order) {
                                                                                                                                                                                                                            int[] rank = new int[26];

                                                                                                                                                                                                                                    // Store the rank of each character
                                                                                                                                                                                                                                            for (int i = 0; i < 26; i++) {
                                                                                                                                                                                                                                                        rank[order.charAt(i) - 'a'] = i;
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                        // Compare every adjacent pair of words
                                                                                                                                                                                                                                                                                for (int i = 1; i < words.length; i++) {
                                                                                                                                                                                                                                                                                            if (!isSorted(words[i - 1], words[i], rank)) {
                                                                                                                                                                                                                                                                                                            return false;
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                        return true;
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                private boolean isSorted(String a, String b, int[] rank) {
                                                                                                                                                                                                                                                                                                                                                        int m = a.length(), n = b.length();
                                                                                                                                                                                                                                                                                                                                                                int len = Math.min(m, n);

                                                                                                                                                                                                                                                                                                                                                                        for (int i = 0; i < len; i++) {
                                                                                                                                                                                                                                                                                                                                                                                    char c1 = a.charAt(i);
                                                                                                                                                                                                                                                                                                                                                                                                char c2 = b.charAt(i);

                                                                                                                                                                                                                                                                                                                                                                                                            if (c1 != c2) {
                                                                                                                                                                                                                                                                                                                                                                                                                            return rank[c1 - 'a'] < rank[c2 - 'a'];
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Prefix case
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return m <= n;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                             