class Solution {
        public String foreignDictionary(String[] words) {

                Map<Character, Set<Character>> graph = new HashMap<>();
                        Map<Character, Integer> indegree = new HashMap<>();

                                // Initialize graph
                                        for (String word : words) {
                                                    for (char ch : word.toCharArray()) {
                                                                    graph.putIfAbsent(ch, new HashSet<>());
                                                                                    indegree.putIfAbsent(ch, 0);
                                                                                                }
                                                                                                        }

                                                                                                                // Build graph
                                                                                                                        for (int i = 0; i < words.length - 1; i++) {
                                                                                                                                    String w1 = words[i];
                                                                                                                                                String w2 = words[i + 1];

                                                                                                                                                            if (w1.length() > w2.length() && w1.startsWith(w2))
                                                                                                                                                                            return "";

                                                                                                                                                                                        int len = Math.min(w1.length(), w2.length());

                                                                                                                                                                                                    for (int j = 0; j < len; j++) {
                                                                                                                                                                                                                    char c1 = w1.charAt(j);
                                                                                                                                                                                                                                    char c2 = w2.charAt(j);

                                                                                                                                                                                                                                                    if (c1 != c2) {
                                                                                                                                                                                                                                                                        if (!graph.get(c1).contains(c2)) {
                                                                                                                                                                                                                                                                                                graph.get(c1).add(c2);
                                                                                                                                                                                                                                                                                                                        indegree.put(c2, indegree.get(c2) + 1);
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                            Queue<Character> q = new LinkedList<>();

                                                                                                                                                                                                                                                                                                                                                                                                                    for (char ch : indegree.keySet()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                if (indegree.get(ch) == 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                q.offer(ch);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                StringBuilder ans = new StringBuilder();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while (!q.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    char curr = q.poll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ans.append(curr);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (char nei : graph.get(curr)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            indegree.put(nei, indegree.get(nei) - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (indegree.get(nei) == 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                q.offer(nei);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return ans.length() == indegree.size() ? ans.toString() : "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
