class Solution {

        class DSU {
                int[] parent;

                        DSU(int n) {
                                    parent = new int[n];

                                                for(int i = 0; i < n; i++)
                                                                parent[i] = i;
                                                                        }

                                                                                int find(int x) {
                                                                                            if(parent[x] != x)
                                                                                                            parent[x] = find(parent[x]);

                                                                                                                        return parent[x];
                                                                                                                                }

                                                                                                                                        void union(int a, int b) {
                                                                                                                                                    int pa = find(a);
                                                                                                                                                                int pb = find(b);

                                                                                                                                                                            if(pa != pb)
                                                                                                                                                                                            parent[pb] = pa;
                                                                                                                                                                                                    }
                                                                                                                                                                                                        }


                                                                                                                                                                                                            public boolean canTraverseAllPairs(int[] nums) {

                                                                                                                                                                                                                    int n = nums.length;

                                                                                                                                                                                                                            // single element always connected
                                                                                                                                                                                                                                    if(n == 1)
                                                                                                                                                                                                                                                return true;


                                                                                                                                                                                                                                                        DSU dsu = new DSU(n);

                                                                                                                                                                                                                                                                HashMap<Integer, Integer> map = new HashMap<>();
                                                                                                                                                                                                                                                                        // prime factor -> first index having this factor


                                                                                                                                                                                                                                                                                for(int i = 0; i < n; i++) {

                                                                                                                                                                                                                                                                                            int num = nums[i];

                                                                                                                                                                                                                                                                                                        HashSet<Integer> factors = new HashSet<>();

                                                                                                                                                                                                                                                                                                                    for(int p = 2; p * p <= num; p++) {

                                                                                                                                                                                                                                                                                                                                    if(num % p == 0) {

                                                                                                                                                                                                                                                                                                                                                        factors.add(p);

                                                                                                                                                                                                                                                                                                                                                                            while(num % p == 0)
                                                                                                                                                                                                                                                                                                                                                                                                    num /= p;
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                            if(num > 1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            factors.add(num);


                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for(int factor : factors) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(map.containsKey(factor)) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dsu.union(i, map.get(factor));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                map.put(factor, i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int root = dsu.find(0);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for(int i = 1; i < n; i++) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(dsu.find(i) != root)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
