

class Solution {
    public int maxAreaOfIsland(int[][] grid) {
            int rows = grid.length;
                    int cols = grid[0].length;
                            int maxArea = 0;

                                    int[][] dir = {{1,0},{-1,0},{0,1},{0,-1}};

                                            for (int i = 0; i < rows; i++) {
                                                        for (int j = 0; j < cols; j++) {

                                                                        if (grid[i][j] == 1) {
                                                                                            int area = 0;

                                                                                                                Stack<int[]> stack = new Stack<>();
                                                                                                                                    stack.push(new int[]{i, j});
                                                                                                                                                        grid[i][j] = 0;

                                                                                                                                                                            while (!stack.isEmpty()) {
                                                                                                                                                                                                    int[] cur = stack.pop();
                                                                                                                                                                                                                            area++;

                                                                                                                                                                                                                                                    for (int[] d : dir) {
                                                                                                                                                                                                                                                                                int nr = cur[0] + d[0];
                                                                                                                                                                                                                                                                                                            int nc = cur[1] + d[1];

                                                                                                                                                                                                                                                                                                                                        if (nr >= 0 && nc >= 0 &&
                                                                                                                                                                                                                                                                                                                                                                        nr < rows && nc < cols &&
                                                                                                                                                                                                                                                                                                                                                                                                        grid[nr][nc] == 1) {

                                                                                                                                                                                                                                                                                                                                                                                                                                        grid[nr][nc] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        stack.push(new int[]{nr, nc});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    maxArea = Math.max(maxArea, area);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return maxArea;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
